on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: coursier/cache-action
        uses: coursier/cache-action@v6.3
      - name: scala-cli-setup
        uses: VirtusLab/scala-cli-setup@v1.3.2
      - name: test
        run: scala-cli test .
      - name: check formatting
        run: |
          scala-cli fmt --check . || (
            echo "To format code run"
            echo "  scala-cli fmt ."
            exit 1
          )
      - name: package app
        run: scala-cli .github/scripts/package.sc
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: launchers
          path: artifacts
          if-no-files-found: error
          retention-days: 2